/*

 BKG_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char BKG_TILES[] =
{
  0x00,0x00,0x00,0x00,0x66,0x00,0x00,0x00,
  0xFF,0xFF,0xFF,0xDB,0xDB,0xFF,0xFF,0xFF,
  0xFF,0x81,0x81,0x81,0xE7,0x81,0x81,0xFF,
  0x00,0x7E,0x7E,0x5A,0x5A,0x7E,0x7E,0x00
};

/* End of BKG_TILES.C */
